In [1]:
# if "Intel" in cpuinfo.get_cpu_info()['brand_raw']:
from sklearnex import patch_sklearn
patch_sklearn()

import os
os.chdir("..")

import random
from multiprocessing.dummy import Pool
from pathlib import Path
from typing import Counter

import cv2
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy
import seaborn as sns
from skin_lesion_cad.data.BOVW import (BagofWords, ColorDescriptor,
                                       DenseDescriptor, DescriptorsTransformer,
                                       LBPDescriptor)
from skin_lesion_cad.features.colour import (ColorFeaturesDescriptor,
                                             ColorFeaturesExtractor)
from skin_lesion_cad.features.texture import get_glcm, glcm_features, lbph
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.cluster import KMeans
from sklearn.metrics import (accuracy_score, classification_report,
                             cohen_kappa_score, confusion_matrix, f1_score,
                             precision_score)
from sklearn.model_selection import KFold, StratifiedKFold, train_test_split
from sklearn.svm import SVC
from tqdm import tqdm

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)
Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)


In [2]:
KP_SIZE = 25
color_spaces = {'bgr':cv2.COLOR_RGB2BGR, 'hsv':cv2.COLOR_RGB2HSV, 'YCrCb':cv2.COLOR_RGB2YCrCb}

root_path = Path().resolve()

chall2_train = root_path/"data/processed/chall2/train"
mel_imgs_all = np.array(list((chall2_train/'mel').glob("*inpaint_0_5.png")))
bcc_imgs_all = np.array(list((chall2_train/'bcc').glob("*inpaint_0_5.png")))
scc_imgs_all = np.array(list((chall2_train/'scc').glob("*inpaint_0_5.png")))
test_imgs_train = np.concatenate([mel_imgs_all, bcc_imgs_all, scc_imgs_all])

chall2_val = root_path/"data/processed/chall2/val"
mel_imgs_all = np.array(list((chall2_val/'mel').glob("*inpaint_0_5.png")))
bcc_imgs_all = np.array(list((chall2_val/'bcc').glob("*inpaint_0_5.png")))
scc_imgs_all = np.array(list((chall2_val/'scc').glob("*inpaint_0_5.png")))
test_imgs_val = np.concatenate([mel_imgs_all, bcc_imgs_all, scc_imgs_all])

print(f'Train images {len(test_imgs_train)}, Validation images {len(test_imgs_val)}')

Train images 5082, Validation images 1270


In [3]:
chall2_test = root_path/"data/processed/chall2"
test_imgs_TEST = np.array(list((chall2_test/'test').glob("*inpaint_0_5.png")))
print(f'Test images {len(test_imgs_TEST)}')

Test images 226


## Getting Color Descriptors for Images for BoW

Either rung the section below or load the saved pickle file.from one below it.

### Calculate features from scratch

In [4]:
brisk = cv2.BRISK_create(thresh=30, octaves=0)

# define descriptors used for BoW
# use gaussian sampling
dense_desc = DenseDescriptor(descriptor=None, min_keypoints=100,
                             max_keypoints=500, kp_size=KP_SIZE,
                             sample_method='gaussian')


dense_color = ColorDescriptor(dense_desc, color_spaces, meanshift=None,
                              min_keypoints=100, max_keypoints=500,
                              kp_size=25,
                              sample_method='gaussian')

In [5]:
def _load_and_extract_des_color(x):
    image_path, descriptor = x
    im = cv2.imread(str(image_path))
    if 'bcc' in str(image_path):
        img_cls = 0
    elif 'mel' in str(image_path):
        img_cls = 1
    else:
        img_cls = 2

    kpts, des = descriptor.detectAndCompute(im, None)
    return (des, img_cls, image_path.name)

In [ ]:
descriptors_color_train = []
img_classes_color_train = []
img_names_color_train = []

# COLOR FOR TRAIN
with Pool(8) as pool:
    for (des, img_cls, img_name) in tqdm(pool.imap(_load_and_extract_des_color,
                                       zip(test_imgs_train,
                                           [dense_color]*len(test_imgs_train))), total=len(test_imgs_train)):
        descriptors_color_train.append(des)
        img_classes_color_train.append(img_cls)
        img_names_color_train.append(img_name)
        
pd.to_pickle((descriptors_color_train, img_classes_color_train, img_names_color_train), 'descriptors_color_train_all_train.pkl')

In [ ]:
descriptors_color_val = []
img_classes_color_val = []
img_names_color_val = []

# COLOR FOR VALIDATION
with Pool(8) as pool:
    for (des, img_cls, img_name) in tqdm(pool.imap(_load_and_extract_des_color,
                                       zip(test_imgs_val,
                                           [dense_color]*len(test_imgs_val))), total=len(test_imgs_val)):
        descriptors_color_val.append(des)
        img_classes_color_val.append(img_cls)
        img_names_color_val.append(img_name)
        
pd.to_pickle((descriptors_color_val, img_classes_color_val, img_names_color_val), 'descriptors_color_val_all_val_gauss.pkl')

In [6]:
descriptors_color_TEST = []
img_classes_color_TEST = []
img_names_color_TEST = []

# COLOR FOR TESTIDATION
with Pool(8) as pool:
    for (des, img_cls, img_name) in tqdm(pool.imap(_load_and_extract_des_color,
                                       zip(test_imgs_TEST,
                                           [dense_color]*len(test_imgs_TEST))), total=len(test_imgs_TEST)):
        descriptors_color_TEST.append(des)
        img_classes_color_TEST.append(img_cls)
        img_names_color_TEST.append(img_name)
        
pd.to_pickle((descriptors_color_TEST, img_classes_color_TEST, img_names_color_TEST), 'descriptors_color_TEST.pkl')

100%|██████████| 226/226 [01:18<00:00,  2.89it/s]


### Load the dump

In [8]:
descriptors_color_train, img_classes_color_train, img_names_color_train = pd.read_pickle('descriptors_color_all_train.pkl')
descriptors_color_val, img_classes_color_val, img_names_color_val = pd.read_pickle('descriptors_color_all_val_gauss.pkl')
print(len(descriptors_color_train), len(descriptors_color_val))

5082 1270


## Creating and calculating BoW

In [9]:
descriptors_color_train = np.asarray(descriptors_color_train)
descriptors_color_val = np.asarray(descriptors_color_val)


bow_color = BagofWords(n_words=100, n_jobs=-1, random_state=42)
train_BoWed = bow_color.fit_transform(descriptors_color_train, img_classes_color_train) 
val_BoWed = bow_color.transform(descriptors_color_val)

# creating datafrains that contain the BoW features and the image class for all images
bow_train = pd.DataFrame(train_BoWed.toarray(), columns=[f'bow_{i}' for i in range(train_BoWed.shape[1])])
bow_val = pd.DataFrame(val_BoWed.toarray(), columns=[f'bow_{i}' for i in range(val_BoWed.shape[1])])

bow_train['class'] = img_classes_color_train
bow_val['class'] = img_classes_color_val

bow_train['name'] = img_names_color_train
bow_val['name'] = img_names_color_val


# classification and evaluation
svc = SVC(kernel='rbf', C=1, random_state=42, probability=False, class_weight='balanced')
svc.fit(bow_train.drop(['class', 'name'], axis=1), bow_train['class'])
y_pred = svc.predict(bow_val.drop(['class', 'name'], axis=1))
y_pred_train = svc.predict(bow_train.drop(['class', 'name'], axis=1))

print(confusion_matrix(bow_val['class'], y_pred))
print('Train f1_weighted',f1_score(bow_train['class'], y_pred_train, average='weighted'))
print('Validation f1_weighted', f1_score(bow_val['class'], y_pred, average='weighted'))
print('Train kappa',cohen_kappa_score(bow_train['class'], y_pred_train))
print('Validation kappa', cohen_kappa_score(bow_val['class'], y_pred))

[[399  98   1]
 [126 552   0]
 [ 63  26   5]]
Train f1_weighted 0.785624708932611
Validation f1_weighted 0.7308260342898841
Train kappa 0.6381381740298608
Validation kappa 0.5369398409631391


Making final BOW on train+val

In [10]:
descriptors_color_train = np.asarray(descriptors_color_train)
descriptors_color_val = np.asarray(descriptors_color_val)

ALL_descrps = np.vstack([descriptors_color_train, descriptors_color_val])
ALL_img_classes = np.hstack([img_classes_color_train, img_classes_color_val])

print(descriptors_color_train.shape, descriptors_color_val.shape, ALL_descrps.shape, ALL_img_classes.shape)
bow_color = BagofWords(n_words=100, n_jobs=-1, random_state=42)
train_BoWed = bow_color.fit_transform(ALL_descrps, ALL_img_classes) 


TEST_BoWed = bow_color.transform(descriptors_color_TEST)
bow_TEST = pd.DataFrame(TEST_BoWed.toarray(), columns=[f'bow_{i}' for i in range(val_BoWed.shape[1])])
bow_TEST['name'] = img_names_color_TEST

(5082, 100, 72) (1270, 100, 72) (6352, 100, 72) (6352,)


## Extracting color features (global)

In [12]:
def extract_color(image_path):
    cfe = ColorFeaturesExtractor(color_spaces)
    im = cv2.imread(str(image_path))
    im = im[im.shape[0]//4:im.shape[0]*3//4, im.shape[1]//4:im.shape[1]*3//4, :]

    
    mask = np.ones_like(im[:,:,0]) #cv2.imread(str(image_path).replace('inpaint', 'mask'))
    if 'bcc' in str(image_path):
        img_cls = 0
    elif 'mel' in str(image_path):
        img_cls = 1
    else:
        img_cls = 2

    des = cfe.extract_masked(im, mask)

    return (des, img_cls, image_path.name)

colf_train = []
colc_train = []
colnam_train = []
with Pool(8) as pool:
    for (des, img_cls, img_name) in tqdm(pool.imap(extract_color,
                                       test_imgs_train), total=len(test_imgs_train)):
        colf_train.append(des)
        colc_train.append(img_cls)
        colnam_train.append(img_name)

100%|██████████| 5082/5082 [00:51<00:00, 98.98it/s] 


In [13]:
colf_val = []
colc_val = []
colnam_val = []
with Pool(8) as pool:
    for (des, img_cls, img_name) in tqdm(pool.imap(extract_color,
                                       test_imgs_val), total=len(test_imgs_val)):
        colf_val.append(des)
        colc_val.append(img_cls)
        colnam_val.append(img_name)

100%|██████████| 1270/1270 [00:11<00:00, 106.07it/s]


In [14]:
color_df_train = pd.DataFrame(colf_train)
color_df_train['name'] = colnam_train
color_df_train['class'] = colc_train

color_df_val = pd.DataFrame(colf_val)
color_df_val['name'] = colnam_val
color_df_val['class'] = colc_val


scaler = DescriptorsTransformer(imputation=None)
X_train = scaler.fit_transform(color_df_train.drop(['class', 'name'], axis=1))
X_test = scaler.transform(color_df_val.drop(['class', 'name'], axis=1))

svc = SVC(kernel='rbf', C=1, random_state=42, probability=False, class_weight='balanced')
svc.fit(X_train, color_df_train['class'])
y_pred = svc.predict(X_test)
y_pred_train = svc.predict(X_train)

print(confusion_matrix(color_df_val['class'], y_pred))
print('Train f1_weighted',f1_score(color_df_train['class'], y_pred_train, average='weighted'))
print('Validation f1_weighted', f1_score(color_df_val['class'], y_pred, average='weighted'))
print('Train kappa',cohen_kappa_score(color_df_train['class'], y_pred_train))
print('Validation kappa', cohen_kappa_score(color_df_val['class'], y_pred))

[[435  61   2]
 [ 62 616   0]
 [ 57  31   6]]
Train f1_weighted 0.8190181201191215
Validation f1_weighted 0.8075351154802809
Train kappa 0.706336521578109
Validation kappa 0.6840692709452578


In [15]:
colf_TEST = []
colc_TEST = []
colnam_TEST = []
with Pool(8) as pool:
    for (des, img_cls, img_name) in tqdm(pool.imap(extract_color,
                                       test_imgs_TEST), total=len(test_imgs_TEST)):
        colf_TEST.append(des)
        colc_TEST.append(img_cls)
        colnam_TEST.append(img_name)

100%|██████████| 226/226 [00:01<00:00, 175.08it/s]


In [16]:
color_df_TEST = pd.DataFrame(colf_TEST)
color_df_TEST['name'] = colnam_TEST
color_df_TEST['class'] = colc_TEST

```
Preprocessed 

[[435  61   2]
 [ 62 616   0]
 [ 57  31   6]]
Train f1_weighted 0.8190181201191215
Validation f1_weighted 0.8075351154802809
Train kappa 0.706336521578109
Validation kappa 0.6840692709452578

```

## Extracting texture features

### GLCM

In [17]:
def extract_text(image_path):
    im = cv2.imread(str(image_path), cv2.IMREAD_GRAYSCALE)
    if 'bcc' in str(image_path):
        img_cls = 0
    elif 'mel' in str(image_path):
        img_cls = 1
    else:
        img_cls = 2

    des = glcm_features(im)

    return (des, img_cls, image_path.name)

txtf_train = []
txtcl_train = []
txtnam_train = []
with Pool(8) as pool:
    for (des, img_cls, img_name) in tqdm(pool.imap(extract_text,
                                       test_imgs_train), total=len(test_imgs_train)):
        txtf_train.append(des)
        txtcl_train.append(img_cls)
        txtnam_train.append(img_name)
        
txtf_val = []
txtcl_val = []
txtnam_val = []
with Pool(8) as pool:
    for (des, img_cls, img_name) in tqdm(pool.imap(extract_text,
                                       test_imgs_val), total=len(test_imgs_val)):
        txtf_val.append(des)
        txtcl_val.append(img_cls)
        txtnam_val.append(img_name)

100%|██████████| 1270/1270 [00:44<00:00, 28.43it/s]


In [18]:
# unrevelling the dataframe
txtf_exp_train = []
for i in range(len(txtf_train)):
    res = dict()
    for feat in txtf_train[i].keys():
        for featvalidx, featval in enumerate(txtf_train[i][feat][0]):
            res[f'{feat}_{featvalidx}'] = featval
    txtf_exp_train.append(res)
    
txtf_exp_val = []
for i in range(len(txtf_val)):
    res = dict()
    for feat in txtf_val[i].keys():
        for featvalidx, featval in enumerate(txtf_val[i][feat][0]):
            res[f'{feat}_{featvalidx}'] = featval
    txtf_exp_val.append(res)
    
glcm_df_train = pd.DataFrame(txtf_exp_train)
glcm_df_train['name'] = txtnam_train
glcm_df_train['class'] = txtcl_train

glcm_df_val = pd.DataFrame(txtf_exp_val)
glcm_df_val['name'] = txtnam_val
glcm_df_val['class'] = txtcl_val

glcm_df_train

contrast_0  contrast_1  contrast_2  contrast_3  contrast_4  contrast_5  \
0      37.024355   25.972513   43.313558   26.060410  118.161507  156.938394   
1      39.624743   25.582948   43.126007   24.981051  156.690424  199.892093   
2       9.573169    5.522761    8.325065    5.094060   38.135228   45.484275   
3       7.913362    4.657573    4.966261    4.397605   17.275668   18.531984   
4      61.821193   57.422778   83.971465   27.830506  135.542539  195.146065   
...          ...         ...         ...         ...         ...         ...   
5077   17.305599    9.375956   18.256648    9.750893   95.621306  120.252724   
5078  110.249873   76.169643  106.220314   67.206358  276.378154  329.689113   
5079   71.730708   50.245536   67.282750   45.176601  176.607638  221.991149   
5080    5.123231    3.301443    4.154845    2.888780   14.336095   15.520960   
5081   40.694109   26.429258   41.521211   28.940471   87.124008   91.851734   

      contrast_6  contrast_7  contrast_8  contrast_9  ...    ASM_12    ASM_13  \
0     135.077561  146.720879  182.628714  211.429630  ...  0.000287  0.000281   
1     166.556814  198.263613  275.062040  291.341476  ...  0.019485  0.018741   
2      35.530526   43.847092   62.777885   63.431922  ...  0.001206  0.001232   
3      12.801671   17.120253   22.089871   22.451459  ...  0.003025  0.002916   
4     211.042939  190.022869  188.776504  255.332126  ...  0.000772  0.000679   
...          ...         ...         ...         ...  ...       ...       ...   
5077   98.537587  125.108008  178.694918  181.778159  ...  0.102958  0.101529   
5078  261.978182  291.673964  371.572423  400.124006  ...  0.000274  0.000268   
5079  181.311182  190.074508  247.303512  285.942912  ...  0.000249  0.000246   
5080   11.450798   13.560671   19.633130   18.993040  ...  0.002507  0.002571   
5081   84.943061   96.476091  112.112461  108.707473  ...  0.000400  0.000410   

        ASM_14    ASM_15    ASM_16    ASM_17    ASM_18    ASM_19  \
0     0.000273  0.000278  0.000226  0.000215  0.000216  0.000209   
1     0.020110  0.018831  0.016542  0.015293  0.017506  0.015435   
2     0.001277  0.001300  0.001043  0.001052  0.001092  0.001113   
3     0.003001  0.003151  0.002636  0.002394  0.002553  0.002647   
4     0.000654  0.000733  0.000622  0.000519  0.000515  0.000556   
...        ...       ...       ...       ...       ...       ...   
5077  0.104787  0.101549  0.095469  0.092639  0.098866  0.092519   
5078  0.000272  0.000279  0.000235  0.000224  0.000235  0.000234   
5079  0.000253  0.000257  0.000215  0.000208  0.000220  0.000217   
5080  0.002829  0.002762  0.002169  0.002184  0.002427  0.002333   
5081  0.000400  0.000395  0.000339  0.000348  0.000345  0.000326   

                          name  class  
0     mel02171_inpaint_0_5.png      1  
1     mel01400_inpaint_0_5.png      1  
2     mel00176_inpaint_0_5.png      1  
3     mel02216_inpaint_0_5.png      1  
4     mel00728_inpaint_0_5.png      1  
...                        ...    ...  
5077  scc00027_inpaint_0_5.png      2  
5078  scc00376_inpaint_0_5.png      2  
5079  scc00239_inpaint_0_5.png      2  
5080  scc00130_inpaint_0_5.png      2  
5081  scc00149_inpaint_0_5.png      2  

[5082 rows x 122 columns]

In [19]:
scaler = DescriptorsTransformer(None)
X_train = scaler.fit_transform(glcm_df_train.drop(['class', 'name'], axis=1))
X_test = scaler.transform(glcm_df_val.drop(['class', 'name'], axis=1))

svc = SVC(kernel='rbf', C=1, random_state=42, probability=False, class_weight='balanced')
svc.fit(X_train, glcm_df_train['class'])
y_pred = svc.predict(X_test)
y_pred_train = svc.predict(X_train)

print(confusion_matrix(glcm_df_val['class'], y_pred))
print('Train f1_weighted',f1_score(glcm_df_train['class'], y_pred_train, average='weighted'))
print('Validation f1_weighted', f1_score(glcm_df_val['class'], y_pred, average='weighted'))
print('Train kappa',cohen_kappa_score(glcm_df_train['class'], y_pred_train))
print('Validation kappa', cohen_kappa_score(glcm_df_val['class'], y_pred))

[[347 151   0]
 [147 531   0]
 [ 60  34   0]]
Train f1_weighted 0.6709994708774802
Validation f1_weighted 0.6653965548931365
Train kappa 0.42462073093515984
Validation kappa 0.41537883413969656


Processed

```
[[347 151   0]
 [147 531   0]
 [ 60  34   0]]
Train f1_weighted 0.6709994708774802
Validation f1_weighted 0.6653965548931365
Train kappa 0.42462073093515984
Validation kappa 0.41537883413969656
```

In [20]:
txtf_TEST = []
txtcl_TEST = []
txtnam_TEST = []
with Pool(8) as pool:
    for (des, img_cls, img_name) in tqdm(pool.imap(extract_text,
                                       test_imgs_TEST), total=len(test_imgs_TEST)):
        txtf_TEST.append(des)
        txtcl_TEST.append(img_cls)
        txtnam_TEST.append(img_name)

100%|██████████| 226/226 [00:07<00:00, 30.78it/s]


In [21]:
# unrevelling the dataframe

    
txtf_exp_TEST = []
for i in range(len(txtf_TEST)):
    res = dict()
    for feat in txtf_TEST[i].keys():
        for featTESTidx, featTEST in enumerate(txtf_TEST[i][feat][0]):
            res[f'{feat}_{featTESTidx}'] = featTEST
    txtf_exp_TEST.append(res)


glcm_df_TEST = pd.DataFrame(txtf_exp_TEST)
glcm_df_TEST['name'] = txtnam_TEST
glcm_df_TEST['class'] = txtcl_TEST

glcm_df_train

contrast_0  contrast_1  contrast_2  contrast_3  contrast_4  contrast_5  \
0      37.024355   25.972513   43.313558   26.060410  118.161507  156.938394   
1      39.624743   25.582948   43.126007   24.981051  156.690424  199.892093   
2       9.573169    5.522761    8.325065    5.094060   38.135228   45.484275   
3       7.913362    4.657573    4.966261    4.397605   17.275668   18.531984   
4      61.821193   57.422778   83.971465   27.830506  135.542539  195.146065   
...          ...         ...         ...         ...         ...         ...   
5077   17.305599    9.375956   18.256648    9.750893   95.621306  120.252724   
5078  110.249873   76.169643  106.220314   67.206358  276.378154  329.689113   
5079   71.730708   50.245536   67.282750   45.176601  176.607638  221.991149   
5080    5.123231    3.301443    4.154845    2.888780   14.336095   15.520960   
5081   40.694109   26.429258   41.521211   28.940471   87.124008   91.851734   

      contrast_6  contrast_7  contrast_8  contrast_9  ...    ASM_12    ASM_13  \
0     135.077561  146.720879  182.628714  211.429630  ...  0.000287  0.000281   
1     166.556814  198.263613  275.062040  291.341476  ...  0.019485  0.018741   
2      35.530526   43.847092   62.777885   63.431922  ...  0.001206  0.001232   
3      12.801671   17.120253   22.089871   22.451459  ...  0.003025  0.002916   
4     211.042939  190.022869  188.776504  255.332126  ...  0.000772  0.000679   
...          ...         ...         ...         ...  ...       ...       ...   
5077   98.537587  125.108008  178.694918  181.778159  ...  0.102958  0.101529   
5078  261.978182  291.673964  371.572423  400.124006  ...  0.000274  0.000268   
5079  181.311182  190.074508  247.303512  285.942912  ...  0.000249  0.000246   
5080   11.450798   13.560671   19.633130   18.993040  ...  0.002507  0.002571   
5081   84.943061   96.476091  112.112461  108.707473  ...  0.000400  0.000410   

        ASM_14    ASM_15    ASM_16    ASM_17    ASM_18    ASM_19  \
0     0.000273  0.000278  0.000226  0.000215  0.000216  0.000209   
1     0.020110  0.018831  0.016542  0.015293  0.017506  0.015435   
2     0.001277  0.001300  0.001043  0.001052  0.001092  0.001113   
3     0.003001  0.003151  0.002636  0.002394  0.002553  0.002647   
4     0.000654  0.000733  0.000622  0.000519  0.000515  0.000556   
...        ...       ...       ...       ...       ...       ...   
5077  0.104787  0.101549  0.095469  0.092639  0.098866  0.092519   
5078  0.000272  0.000279  0.000235  0.000224  0.000235  0.000234   
5079  0.000253  0.000257  0.000215  0.000208  0.000220  0.000217   
5080  0.002829  0.002762  0.002169  0.002184  0.002427  0.002333   
5081  0.000400  0.000395  0.000339  0.000348  0.000345  0.000326   

                          name  class  
0     mel02171_inpaint_0_5.png      1  
1     mel01400_inpaint_0_5.png      1  
2     mel00176_inpaint_0_5.png      1  
3     mel02216_inpaint_0_5.png      1  
4     mel00728_inpaint_0_5.png      1  
...                        ...    ...  
5077  scc00027_inpaint_0_5.png      2  
5078  scc00376_inpaint_0_5.png      2  
5079  scc00239_inpaint_0_5.png      2  
5080  scc00130_inpaint_0_5.png      2  
5081  scc00149_inpaint_0_5.png      2  

[5082 rows x 122 columns]

### LBP

In [22]:
def extract_lbp(image_path):
    im = cv2.imread(str(image_path), cv2.IMREAD_GRAYSCALE)
    
    # select central half of the image
    im = im[im.shape[0]//4:im.shape[0]*3//4, im.shape[1]//4:im.shape[1]*3//4]
    if 'bcc' in str(image_path):
        img_cls = 0
    elif 'mel' in str(image_path):
        img_cls = 1
    else:
        img_cls = 2

    des = lbph(im)

    return (des, img_cls, image_path.name)

txtf_train = []
txtcl_train = []
txtnam_train = []
with Pool(8) as pool:
    for (des, img_cls, img_name) in tqdm(pool.imap(extract_lbp,
                                       test_imgs_train), total=len(test_imgs_train)):
        txtf_train.append(des)
        txtcl_train.append(img_cls)
        txtnam_train.append(img_name)
        
txtf_val = []
txtcl_val = []
txtnam_val = []
with Pool(8) as pool:
    for (des, img_cls, img_name) in tqdm(pool.imap(extract_lbp,
                                       test_imgs_val), total=len(test_imgs_val)):
        txtf_val.append(des)
        txtcl_val.append(img_cls)
        txtnam_val.append(img_name)
        
   


100%|██████████| 1270/1270 [00:33<00:00, 38.40it/s]


In [23]:
lbp_df_train = pd.DataFrame(txtf_train, columns=[f'lbp_{i}' for i in range(len(txtf_train[0]))])
lbp_df_train['name'] = txtnam_train
lbp_df_train['class'] = txtcl_train

lbp_df_val = pd.DataFrame(txtf_val, columns=[f'lbp_{i}' for i in range(len(txtf_train[0]))])
lbp_df_val['name'] = txtnam_val
lbp_df_val['class'] = txtcl_val

lbp_df_train

lbp_0     lbp_1     lbp_2     lbp_3     lbp_4     lbp_5     lbp_6  \
0     0.027857  0.010952  0.010000  0.011429  0.011786  0.013512  0.016071   
1     0.043915  0.016174  0.013763  0.014893  0.011902  0.012543  0.011124   
2     0.032272  0.011810  0.009689  0.010071  0.010452  0.012543  0.013748   
3     0.028000  0.014404  0.010208  0.010422  0.009918  0.012131  0.011459   
4     0.030893  0.011548  0.012917  0.014583  0.012381  0.012083  0.014226   
...        ...       ...       ...       ...       ...       ...       ...   
5077  0.020889  0.009964  0.007324  0.006836  0.006378  0.008377  0.008240   
5078  0.042857  0.012857  0.013571  0.016429  0.013869  0.017679  0.016607   
5079  0.037738  0.015357  0.013036  0.013512  0.012738  0.014048  0.013333   
5080  0.030792  0.014221  0.010391  0.010437  0.011429  0.012436  0.011932   
5081  0.055952  0.016905  0.016607  0.017262  0.015952  0.013393  0.012917   

         lbp_7     lbp_8     lbp_9  ...   lbp_142   lbp_143   lbp_144  \
0     0.017024  0.016071  0.019881  ...  0.057798  0.137679  0.202857   
1     0.012360  0.012299  0.013962  ...  0.058426  0.129028  0.167236   
2     0.015564  0.016418  0.019989  ...  0.038605  0.131165  0.179031   
3     0.013794  0.013474  0.015793  ...  0.037048  0.107910  0.118851   
4     0.013036  0.014345  0.017321  ...  0.054583  0.137381  0.210000   
...        ...       ...       ...  ...       ...       ...       ...   
5077  0.011292  0.010269  0.015030  ...  0.027344  0.128677  0.183090   
5078  0.016131  0.018631  0.017917  ...  0.072083  0.136369  0.204286   
5079  0.015357  0.015119  0.017262  ...  0.080536  0.133869  0.156369   
5080  0.013626  0.012604  0.016113  ...  0.028625  0.112717  0.127106   
5081  0.016726  0.012262  0.015714  ...  0.071131  0.132738  0.157083   

       lbp_145   lbp_146   lbp_147   lbp_148   lbp_149  \
0     0.175655  0.091012  0.070714  0.073929  0.099405   
1     0.158142  0.099792  0.083542  0.084488  0.114365   
2     0.198639  0.096130  0.088089  0.097214  0.099976   
3     0.172272  0.097839  0.104355  0.134613  0.132614   
4     0.181071  0.085774  0.066726  0.075833  0.100655   
...        ...       ...       ...       ...       ...   
5077  0.201706  0.082962  0.087830  0.122787  0.096771   
5078  0.167917  0.095179  0.063571  0.060417  0.098869   
5079  0.137976  0.087440  0.073988  0.075357  0.127262   
5080  0.184418  0.096832  0.104324  0.146729  0.117432   
5081  0.144226  0.091429  0.076548  0.081667  0.131548   

                          name  class  
0     mel02171_inpaint_0_5.png      1  
1     mel01400_inpaint_0_5.png      1  
2     mel00176_inpaint_0_5.png      1  
3     mel02216_inpaint_0_5.png      1  
4     mel00728_inpaint_0_5.png      1  
...                        ...    ...  
5077  scc00027_inpaint_0_5.png      2  
5078  scc00376_inpaint_0_5.png      2  
5079  scc00239_inpaint_0_5.png      2  
5080  scc00130_inpaint_0_5.png      2  
5081  scc00149_inpaint_0_5.png      2  

[5082 rows x 152 columns]

In [24]:
scaler = DescriptorsTransformer(None)
X_train = scaler.fit_transform(lbp_df_train.drop(['class', 'name'], axis=1))
X_test = scaler.transform(lbp_df_val.drop(['class', 'name'], axis=1))

# X_train = lbp_df_train.drop(['class', 'name'], axis=1)
# X_test = lbp_df_val.drop(['class', 'name'], axis=1)

svc = SVC(kernel='rbf', C=1, random_state=42, probability=False, class_weight='balanced')
svc.fit(X_train, lbp_df_train['class'])
y_pred = svc.predict(X_test)
y_pred_train = svc.predict(X_train)

print(confusion_matrix(lbp_df_val['class'], y_pred))
print('Train f1_weighted',f1_score(lbp_df_train['class'], y_pred_train, average='weighted'))
print('Validation f1_weighted', f1_score(lbp_df_val['class'], y_pred, average='weighted'))
print('Train kappa',cohen_kappa_score(lbp_df_train['class'], y_pred_train))
print('Validation kappa', cohen_kappa_score(lbp_df_val['class'], y_pred))

[[358 140   0]
 [ 94 584   0]
 [ 43  51   0]]
Train f1_weighted 0.7284629130367141
Validation f1_weighted 0.7118855491264938
Train kappa 0.5373175193643275
Validation kappa 0.504649558827027


In [25]:
txtf_TEST = []
txtcl_TEST = []
txtnam_TEST = []
with Pool(8) as pool:
    for (des, img_cls, img_name) in tqdm(pool.imap(extract_lbp,
                                       test_imgs_TEST), total=len(test_imgs_TEST)):
        txtf_TEST.append(des)
        txtcl_TEST.append(img_cls)
        txtnam_TEST.append(img_name)

100%|██████████| 226/226 [00:02<00:00, 100.42it/s]


In [26]:
lbp_df_TEST = pd.DataFrame(txtf_TEST, columns=[f'lbp_{i}' for i in range(len(txtf_train[0]))])
lbp_df_TEST['name'] = txtnam_TEST
lbp_df_TEST['class'] = txtcl_TEST

# Merging BoW and global faetures

In [27]:
merged_df_train = pd.merge(color_df_train.drop(columns=['class']), glcm_df_train, on='name', how='inner')
merged_df_train = pd.merge(merged_df_train, lbp_df_train.drop(columns=['class']), on='name', how='inner').set_index('name')
merged_df_train = pd.merge(merged_df_train, bow_train.drop(columns=['class']), on='name', how='inner').set_index('name')

merged_df_val = pd.merge(color_df_val.drop(columns=['class']), glcm_df_val, on='name', how='inner')
merged_df_val = pd.merge(merged_df_val, lbp_df_val.drop(columns=['class']), on='name', how='inner').set_index('name')
merged_df_val = pd.merge(merged_df_val, bow_val.drop(columns=['class']), on='name', how='inner').set_index('name')


In [28]:
merged_df_TEST = pd.merge(color_df_TEST, glcm_df_TEST.drop(columns=['class']), on='name', how='inner')
merged_df_TEST = pd.merge(merged_df_TEST, lbp_df_TEST.drop(columns=['class']), on='name', how='inner').set_index('name')
merged_df_TEST = pd.merge(merged_df_TEST, bow_TEST, on='name', how='inner').set_index('name')

In [29]:
merged_df_val

bgr_b_mean  bgr_b_std  bgr_b_skew  bgr_b_kurt  \
name                                                                      
mel03088_inpaint_0_5.png  162.672287  61.694851   -0.697348   -1.077998   
mel03261_inpaint_0_5.png  179.156250  30.963547   -1.417106    2.271164   
mel03342_inpaint_0_5.png  146.851044  37.369217    0.167092   -0.346187   
mel03192_inpaint_0_5.png  205.485016  22.085478   -2.884731    8.592208   
mel02715_inpaint_0_5.png  129.766785  23.655115   -0.514049   -0.549720   
...                              ...        ...         ...         ...   
scc00396_inpaint_0_5.png  210.440598  20.715895   -1.605261    2.332138   
scc00465_inpaint_0_5.png  198.687119  37.127995   -2.469665    8.442849   
scc00406_inpaint_0_5.png  196.194717   5.175140   -0.053817   -0.366602   
scc00386_inpaint_0_5.png  181.532272  14.199497   -4.223199   27.627628   
scc00458_inpaint_0_5.png  169.576019  28.345097   -1.165584    0.529389   

                          bgr_b_max  bgr_b_min  bgr_b_entrp  bgr_b_unq  \
name                                                                     
mel03088_inpaint_0_5.png      250.0       19.0    11.006823        227   
mel03261_inpaint_0_5.png      226.0       18.0     9.712302        199   
mel03342_inpaint_0_5.png      245.0       38.0    11.057418        204   
mel03192_inpaint_0_5.png      231.0       64.0    11.083804        154   
mel02715_inpaint_0_5.png      185.0       52.0    11.072948        130   
...                             ...        ...          ...        ...   
scc00396_inpaint_0_5.png      238.0      115.0     9.723982        120   
scc00465_inpaint_0_5.png      247.0        1.0    11.067039        246   
scc00406_inpaint_0_5.png      228.0      169.0    11.090006         49   
scc00386_inpaint_0_5.png      225.0       42.0    11.086805        180   
scc00458_inpaint_0_5.png      230.0       44.0    11.075174        170   

                          bgr_g_mean  bgr_g_std  ...    bow_90    bow_91  \
name                                             ...                       
mel03088_inpaint_0_5.png  150.737137  62.352291  ...  0.000000  0.000000   
mel03261_inpaint_0_5.png  127.307678  43.122520  ...  0.000000  0.000000   
mel03342_inpaint_0_5.png  134.243668  45.439552  ...  0.000000  0.000000   
mel03192_inpaint_0_5.png  193.508499  31.325283  ...  0.000000  0.032401   
mel02715_inpaint_0_5.png   70.831055  27.696409  ...  0.000000  0.000000   
...                              ...        ...  ...       ...       ...   
scc00396_inpaint_0_5.png  168.585052  33.563663  ...  0.203586  0.000000   
scc00465_inpaint_0_5.png  163.411026  35.686066  ...  0.064951  0.000000   
scc00406_inpaint_0_5.png  203.498489   6.349289  ...  0.000000  0.000000   
scc00386_inpaint_0_5.png  135.912949  17.570173  ...  0.031518  0.000000   
scc00458_inpaint_0_5.png  142.984848  31.235464  ...  0.000000  0.025263   

                            bow_92    bow_93    bow_94    bow_95    bow_96  \
name                                                                         
mel03088_inpaint_0_5.png  0.000000  0.064157  0.000000  0.000000  0.000000   
mel03261_inpaint_0_5.png  0.000000  0.000000  0.000000  0.000000  0.021851   
mel03342_inpaint_0_5.png  0.000000  0.403046  0.000000  0.000000  0.000000   
mel03192_inpaint_0_5.png  0.038344  0.043096  0.000000  0.000000  0.031847   
mel02715_inpaint_0_5.png  0.000000  0.000000  0.000000  0.000000  0.000000   
...                            ...       ...       ...       ...       ...   
scc00396_inpaint_0_5.png  0.027240  0.000000  0.763834  0.000000  0.022624   
scc00465_inpaint_0_5.png  0.000000  0.000000  0.000000  0.000000  0.000000   
scc00406_inpaint_0_5.png  0.000000  0.000000  0.000000  0.097542  0.000000   
scc00386_inpaint_0_5.png  0.168686  0.000000  0.000000  0.000000  0.105079   
scc00458_inpaint_0_5.png  0.000000  0.000000  0.000000  0.000000  0.000000   

                          bow_97    bow_98    bow_99  
name                        

In [30]:
merged_df_TEST.to_pickle('merged_df_TEST.pkl')

Evaluating the performance of merged features

In [31]:
X_train = merged_df_train.drop(columns=['class'])
X_test = merged_df_val.drop(columns=['class'])
y_train = merged_df_train['class']
y_test = merged_df_val['class']

scaler = DescriptorsTransformer(None)
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
y_pred_train = svc.predict(X_train)

print(confusion_matrix(glcm_df_val['class'], y_pred))
print('Train f1_weighted',f1_score(glcm_df_train['class'], y_pred_train, average='weighted'))
print('Validation f1_weighted', f1_score(glcm_df_val['class'], y_pred, average='weighted'))
print('Train kappa',cohen_kappa_score(glcm_df_train['class'], y_pred_train))
print('Validation kappa', cohen_kappa_score(glcm_df_val['class'], y_pred))

[[449  47   2]
 [ 74 603   1]
 [ 56  27  11]]
Train f1_weighted 0.8551313288300627
Validation f1_weighted 0.8171845388739531
Train kappa 0.7644150306930817
Validation kappa 0.6958122549859067


In [ ]:
# merged_df_train.to_pickle('merged_df_train.pkl')
# merged_df_val.to_pickle('merged_df_val.pkl')

# Feature selection

In [77]:
merged_df_train = pd.read_pickle('merged_df_train.pkl')
merged_df_val = pd.read_pickle('merged_df_val.pkl')

In [78]:
def check_subst_list(list_str, check_str):
    for l in list_str:
        if l in check_str:
            return True
    return False

feature_classes = {'color':[x for x in merged_df_train.columns if check_subst_list(['bgr', 'hsv', 'YCrCb'],x)],
                   'glcm':[x for x in merged_df_train.columns if check_subst_list(['contrast', 'dissimilarity',
                                                                                   'homogeneity', 'energy',
                                                                                   'correlation', 'ASM'], x)], 
                   'lbp': [x for x in merged_df_train.columns if 'lbp' in x], 
                   'bow':[x for x in merged_df_train.columns if 'bow' in x]}

In [79]:
X_train = merged_df_train.drop(columns=['class'])
X_test = merged_df_val.drop(columns=['class'])
y_train = merged_df_train['class']
y_test = merged_df_val['class']

scaler = DescriptorsTransformer(None)
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train.shape, X_test.shape)

bgr_b_mean  bgr_b_std  bgr_b_skew  bgr_b_kurt  \
name                                                                      
mel03088_inpaint_0_5.png  162.672287  61.694851   -0.697348   -1.077998   
mel03261_inpaint_0_5.png  179.156250  30.963547   -1.417106    2.271164   
mel03342_inpaint_0_5.png  146.851044  37.369217    0.167092   -0.346187   
mel03192_inpaint_0_5.png  205.485016  22.085478   -2.884731    8.592208   
mel02715_inpaint_0_5.png  129.766785  23.655115   -0.514049   -0.549720   
...                              ...        ...         ...         ...   
scc00396_inpaint_0_5.png  210.440598  20.715895   -1.605261    2.332138   
scc00465_inpaint_0_5.png  198.687119  37.127995   -2.469665    8.442849   
scc00406_inpaint_0_5.png  196.194717   5.175140   -0.053817   -0.366602   
scc00386_inpaint_0_5.png  181.532272  14.199497   -4.223199   27.627628   
scc00458_inpaint_0_5.png  169.576019  28.345097   -1.165584    0.529389   

                          bgr_b_max  bgr_b_min  bgr_b_entrp  bgr_b_unq  \
name                                                                     
mel03088_inpaint_0_5.png      250.0       19.0    11.006823        227   
mel03261_inpaint_0_5.png      226.0       18.0     9.712302        199   
mel03342_inpaint_0_5.png      245.0       38.0    11.057418        204   
mel03192_inpaint_0_5.png      231.0       64.0    11.083804        154   
mel02715_inpaint_0_5.png      185.0       52.0    11.072948        130   
...                             ...        ...          ...        ...   
scc00396_inpaint_0_5.png      238.0      115.0     9.723982        120   
scc00465_inpaint_0_5.png      247.0        1.0    11.067039        246   
scc00406_inpaint_0_5.png      228.0      169.0    11.090006         49   
scc00386_inpaint_0_5.png      225.0       42.0    11.086805        180   
scc00458_inpaint_0_5.png      230.0       44.0    11.075174        170   

                          bgr_g_mean  bgr_g_std  ...    bow_90    bow_91  \
name                                             ...                       
mel03088_inpaint_0_5.png  150.737137  62.352291  ...  0.000000  0.000000   
mel03261_inpaint_0_5.png  127.307678  43.122520  ...  0.000000  0.000000   
mel03342_inpaint_0_5.png  134.243668  45.439552  ...  0.000000  0.000000   
mel03192_inpaint_0_5.png  193.508499  31.325283  ...  0.000000  0.032401   
mel02715_inpaint_0_5.png   70.831055  27.696409  ...  0.000000  0.000000   
...                              ...        ...  ...       ...       ...   
scc00396_inpaint_0_5.png  168.585052  33.563663  ...  0.203586  0.000000   
scc00465_inpaint_0_5.png  163.411026  35.686066  ...  0.064951  0.000000   
scc00406_inpaint_0_5.png  203.498489   6.349289  ...  0.000000  0.000000   
scc00386_inpaint_0_5.png  135.912949  17.570173  ...  0.031518  0.000000   
scc00458_inpaint_0_5.png  142.984848  31.235464  ...  0.000000  0.025263   

                            bow_92    bow_93    bow_94    bow_95    bow_96  \
name                                                                         
mel03088_inpaint_0_5.png  0.000000  0.064157  0.000000  0.000000  0.000000   
mel03261_inpaint_0_5.png  0.000000  0.000000  0.000000  0.000000  0.021851   
mel03342_inpaint_0_5.png  0.000000  0.403046  0.000000  0.000000  0.000000   
mel03192_inpaint_0_5.png  0.038344  0.043096  0.000000  0.000000  0.031847   
mel02715_inpaint_0_5.png  0.000000  0.000000  0.000000  0.000000  0.000000   
...                            ...       ...       ...       ...       ...   
scc00396_inpaint_0_5.png  0.027240  0.000000  0.763834  0.000000  0.022624   
scc00465_inpaint_0_5.png  0.000000  0.000000  0.000000  0.000000  0.000000   
scc00406_inpaint_0_5.png  0.000000  0.000000  0.000000  0.097542  0.000000   
scc00386_inpaint_0_5.png  0.168686  0.000000  0.000000  0.000000  0.105079   
scc00458_inpaint_0_5.png  0.000000  0.000000  0.000000  0.000000  0.000000   

                          bow_97    bow_98    bow_99  
name                        